---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
  selector:
    name: web

